dataset:
  channels: 3
  resolution: 64
  path: dataset/DIV2K
  filetype: png
  low_resolution: True
generator:
  feature_maps: 64
train:
  batch_size: 16
  epochs: 10
  hyper_lambda: 0.5
  hyper_eta: 0.5
  lr: 0.001
