# 0. Logging
log: "wandb"

# 1. Dataset Configuration
dataset:
  name: "MNIST"
  channels: 1
  resolution: 32
  path: datasets/FFHQ
  lowres: True

# 2. Network Configuration
network:
  name: "DUMMY"
  Generator:
    input_features:
  Discriminator:

  feature_maps: 64
  latent_vector: 100
  generator_input: 64
  generator_features: 64
  optimizer: "Adam"
  amsgrad: False
  lr: 0.001
  weight_decay: 0
  beta1: 0.9

# 3. Training Configuration
model:
  name: "GAN"
  batch_size: 64
  loss_gan: "vanilla"
  num_epochs: 100
  hyper_lambda: 0.5
  hyper_eta: 0.5
