# 0. Basic Configuration
device: "mps"
log:
  active: True
  project: "my-awesome-project"
  id: "PSNR_HAT_DIFFUSION"

# 1. Dataset Configuration
dataset:
  name: "FFHQ"
  batch_size: 5
  channels: 3
  num_workers: 0
  resolution: 128
  lowres_resolution: 32

# 2. Network Configuration
network:
  name: "HAT"
  net_G:
    img_size: 64
    patch_size: 1
    in_chans: 3
    embed_dim: 96
    depths: [6, 6, 6, 6, 6, 6]
    num_heads: [6, 6, 6, 6, 6, 6]
    window_size: 16
    compress_ratio: 3
    squeeze_factor: 30
    conv_scale: 0.01
    overlap_ratio: 0.5
    mlp_ratio: 4.0
    qkv_bias: true
    qk_scale: null
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.1
    norm_layer: nn.LayerNorm
    ape: false
    patch_norm: true
    use_checkpoint: false
    upscale: 2
    img_range: 1.0
    upsampler: "pixelshuffle"
    resi_connection: "1conv"
  net_D:
    num_in_ch: 3
    num_feat: 64
    skip_connection: true
  net_F:
    model: "vgg"
    feature_layer: 34
    use_bn: False
    use_input_norm: True

# 3. Model Configuration
model:
  name: "ESRGAN"
  optimizer:
    name: "ADAM"
    amsgrad: False
    lr: 0.0001
    weight_decay: 0
    beta1: 0.9
    beta2: 0.999
  loss:
    weight_pixel: 1
    weight_feature: 0
    weight_gan: 0
  scheduler:
    name:
    milestones: [2500, 5000, 10000, 20000]
    gamma: 0.5
  resume:
    active: False
  train:
    num_epochs: 100
