# 0. Basic Configuration
device: "mps"
log:
  active: True
  project: "my-awesome-project"
  id: "Trial_4"

# 1. Dataset Configuration
dataset:
  name: "MNIST"
  batch_size: 64
  channels: 3
  num_workers: 0
  resolution: 64
  lowres_resolution: 32

# 2. Dataset Configuration
network:
  name: "DUMMY"
  generator:
    in_channels: 100
    feat_channels: 128
    out_channels: 1
  discriminator:
    in_channels: 1

# 3. Model Configuration
model:
  name: "GAN"
  optimizer:
    name: "ADAM"
    amsgrad: False
    lr: 0.0001
    weight_decay: 0
    beta1: 0.9
    beta2: 0.999
  loss:
    weight_pixel: 0.01
    weight_feature: 1
    weight_gan: 0.005
  scheduler:
    name: "MultiStepLR"
    milestones: [100, 400, 800, 12000]
    #milestones: [50000, 100000, 200000, 300000]
    gamma: 0.5
  resume:
    active: False
  train:
    num_epochs: 100
